CONTAINER Onoodle
{
	NAME Onoodle;
	INCLUDE Obase;

	GROUP NOODLE_GROUP_TITLE
	{
		GROUP NOODLE_GROUP_KNOT_PROPS
		{
			DEFAULT 1;

			LONG NOODLE_PRESETS
			{
				ANIM OFF;

				CYCLE
				{
					NOODLE_CUSTOM_PRESET;
					NOODLE_PRESET_A_KNOT_23;
					NOODLE_PRESET_A_KNOT_32;
					NOODLE_PRESET_A_KNOT_37;
					NOODLE_PRESET_A_KNOT_94;

					NOODLE_PRESET_B_STAR_A;
					NOODLE_PRESET_B_STAR_B;
					NOODLE_PRESET_B_STAR_C;
					NOODLE_PRESET_B_STAR_D;
					NOODLE_PRESET_B_STAR_E;
					NOODLE_PRESET_B_FIG8_A;
					NOODLE_PRESET_B_FIG8_B;
					NOODLE_PRESET_B_FIG8_C;
					NOODLE_PRESET_B_CIRC_A;
					NOODLE_PRESET_B_CIRC_B;
					NOODLE_PRESET_B_CIRC_C;
					NOODLE_PRESET_B_PAIR_A;
					NOODLE_PRESET_B_PAIR_B;
					NOODLE_PRESET_B_COMP_A;
					NOODLE_PRESET_B_COMP_B;

					NOODLE_PRESET_C_FLEUR_A;
					NOODLE_PRESET_C_FLEUR_B;
					NOODLE_PRESET_C_FLEUR_C;
					NOODLE_PRESET_C_STAR_A;
					NOODLE_PRESET_C_STAR_B;
					NOODLE_PRESET_C_STAR_C;
					NOODLE_PRESET_C_STAR_D;
				}
			}

			SEPARATOR { LINE; }

			LONG NOODLE_TYPE
			{
				ANIM OFF;

				CYCLE
				{
					NOODLE_TYPE_TORUS_A;
					NOODLE_TYPE_TORUS_B;
					NOODLE_TYPE_TORUS_C;
				}
			}

			STRING NOODLE_FORMULA_VIEW { ANIM OFF; CUSTOMGUI MULTISTRING; SCALE_V; WORDWRAP; }

			BOOL NOODLE_FORMULA_SHOW_VALUES { ANIM OFF; }

			SEPARATOR { LINE; }

			REAL NOODLE_VAR_P { UNIT REAL; STEP 1;}
			VECTOR NOODLE_VAR_Q { UNIT REAL; STEP 1;}
			VECTOR NOODLE_VAR_M { UNIT REAL; STEP 0.1;}
			VECTOR NOODLE_VAR_N { UNIT REAL; STEP 0.1;}
			VECTOR NOODLE_VAR_R { UNIT REAL; STEP 1;}
			VECTOR NOODLE_VAR_S { UNIT REAL; STEP 0.1;}
			
			SEPARATOR { LINE; }

			BOOL NOODLE_SIGN_CHANGE { ANIM OFF; }
			BOOL NOODLE_INTERLACING { ANIM OFF; }
			BOOL NOODLE_AUTO_SOLVE { ANIM OFF; }

			SEPARATOR { LINE; }

			LONG NOODLE_POINT_COUNT { STEP 1; }
			VECTOR NOODLE_SIZE { UNIT METER; }
		}

		GROUP NOODLE_GROUP_SPLINE_PROPS
		{
			DEFAULT 1;

			LONG NOODLE_SPLINE_TYPE
			{
				ANIM OFF;

				CYCLE
				{
					NOODLE_SPLINE_TYPE_LINEAR;
					NOODLE_SPLINE_TYPE_CUBIC;
					NOODLE_SPLINE_TYPE_AKIMA;
					NOODLE_SPLINE_TYPE_BSPLINE;
					NOODLE_SPLINE_TYPE_BEZIER;
				}
			}

			BOOL NOODLE_SPLINE_CLOSED { }
		}
	}
}
